// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awkwlagcwdqsefgeltkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3a3dsYWdjd2Rxc2VmZ2VsdGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NTIxODAsImV4cCI6MjA1NjMyODE4MH0.bI8XBercwTVFb1YGK_WJdiuFheeSxQbMr04Ku8Dqqgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);